### ISSUE TITLE
[Missing Block] This... thing...

### ISSUE THREAD

**Issue by DogeisCut** [legowiifun/Geometry-Dash-Unlisted-Objects-in-Editor#10]
Object id 3800, I have no idea what it is, it looks broken, and it's most certainly unlisted.
![image](https://github.com/legowiifun/Geometry-Dash-Unlisted-Objects-in-Editor/assets/23178844/4d37b809-065b-4c80-b2e9-d9def1be5306)

**Comment by legowiifun** [comment]
I just sent an update for approval that adds this block. Through some experimentation, I think this block is a mish-mash of textures, that were squished to 1/4 the normal size on the y axis but not on the x axis. Attached is an image of what it looks like when scaled to 4x on the y axis and 1x on the x axis. 
![image](https://github.com/legowiifun/Geometry-Dash-Unlisted-Objects-in-Editor/assets/7890021/0b3a05b6-bc58-48c2-b245-75d7661aa345)
