### ISSUE TITLE
[Feature Request] Unlisted End trigger

### ISSUE THREAD

**Issue by KorbynTalks** [legowiifun/Geometry-Dash-Unlisted-Objects-in-Editor#11]
Surprisingly, Theres a older version of the End trigger unlisted in the editor, I found it by going through the New Object IDS level by GD Colon.
Comparison:
![image](https://github.com/legowiifun/Geometry-Dash-Unlisted-Objects-in-Editor/assets/138175049/12aab67c-2ae6-49bc-997a-58ff550e821c)
Old Trigger UI:
![image](https://github.com/legowiifun/Geometry-Dash-Unlisted-Objects-in-Editor/assets/138175049/f02d1ccb-61eb-463c-a233-e337e6c3e843)
New Trigger UI:
![image](https://github.com/legowiifun/Geometry-Dash-Unlisted-Objects-in-Editor/assets/138175049/204b2bbb-b9b1-4db2-b1d7-3eaa4a2699b9)

**Comment by KorbynTalks** [comment]
btw the Object ID is 1931

**Comment by legowiifun** [comment]
Firstly, thank you for the Object ID. That makes it a lot easier to add the object to the mod. Next, I have added this object to version 1.2.2 of the mod, and pushed this version to the list of mods to put on the Geode index. I tried to figure out how it worked, but I found that all functionality is missing from it, and it does not do anything.
