### ISSUE TITLE
Mod can't be ported to 2.206 (sad)

### ISSUE THREAD

**Issue by Pololak** [legowiifun/Geometry-Dash-Unlisted-Objects-in-Editor#16]
Well, EditButtonBar::init was inlined in 2.206, so it's impossible to port this mod for 2.206

**Comment by legowiifun** [comment]
I just found a workaround for this that works.

**Comment by Pololak** [comment]
Will it be ported for android?

**Comment by legowiifun** [comment]
I do not have an android device to test with. However, if other people would be willing to test an android version, I would be willing to try to port it.

**Comment by Pololak** [comment]
i can test it

**Comment by legowiifun** [comment]
Try out the latest release.

**Comment by Pololak** [comment]
everything is fine. Nice 👍
