### ISSUE TITLE
[Object Request] Not all unlisted and usable objects are included

### ISSUE THREAD

**Issue by torzod** [legowiifun/Geometry-Dash-Unlisted-Objects-in-Editor#3]
Not all unlisted and usable objects are included in this mod, such as:
* 3DL objects with hitboxes
* Some old ground spikes
* Old sloped ground spikes
* Certain old saws
* Certain old half-blocks ("slabs")
* One specific tile in the old stripey tileset (one with connections up, down, right, and down-right)
* 6 unused bush decoration variants
* The ball of the ball-and-stick decoration objects
* The smallest (¼ block) old fake spike
* The old outline slopes
* Most old slopes
* 6 old color triggers (only the background trigger is distinguishable as of 2.2 by its "tint ground" checkbox, though all work properly. they had individual textures indicating what color channels they effect that were removed and merged to the modern color trigger texture)

These objects can be found in level ID 99215371, though notably the old gears have been converted by 2.2 into modern gears, and the "random in/out" trigger is now no longer visible in normal mode nor collidable, and is now normally obtainable.

To test whether an object is in the editor easily, simply pick a block to build with, unpick it, then click on the desired object. If the object is in the editor, you will be taken to its tab and page and select it to build with. If it is not in the editor, it will be selected to build with without taking you to its tab or page, as it has neither. To distinguish identical objects, you can attempt to place them over each other in Build Mode, and if they are distinct, you will be able to place it, otherwise you will not be able to place an object over itself. (This is mainly relevant for the color triggers, though there are multiple other pairs of duplicate objects.)

**Comment by legowiifun** [comment]
Unfortunately, the old color triggers crash the game when I add them to the triggers tab. This was something I had tried to add to the v1.0 version of the mod. However, I have added most of the other objects listed here in the latest version (I have not added the ball part of the ball-and-stick deco objects yet).

**Comment by torzod** [comment]
thank you very much!
